controller_list:
  - name: leftarm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - leftarm_baserotate
      - leftarm_armrotate
      - leftarm_forearmrotate
      - leftarm_gripperrotate
      - leftarm_gripperpivot
