controller_list:
  - name: fake_leftgripper_group_controller
    joints:
      - leftarm_baserotate
      - leftarm_armrotate
      - leftarm_forearmrotate
      - leftarm_gripperrotate
      - leftarm_gripperpivot