#!/bin/bash
#Author: David Gitz
#Purpose: Launches Software on all Devices

declare -a Devices=("ControlModule1" "dgitzrosmaster")

function launch_device_remote ()
{
    #Remote in to device
    #echo "Going to Remote Launch: roslaunch icarus_rover_v2 "$1".launch"
    launch_command="cd ~ && screen -dmS robot ./scripts/launchDevice -d $1"
    #echo $launch_command
    ssh robot@$1 $launch_command
    
}

function launch_device_local ()
{
    #echo "Going to Local Launch: roslaunch icarus_rover_v2 "$1".launch"
    launch_command="screen -dmS robot ./scripts/launchDevice -d $1"
    eval $launch_command
}

function launch_all_devices()
{
    echo "Launching on all Devices"
    for device in "${Devices[@]}"
    do
        if [ $device != $HOSTNAME ]; then
            launch_device_remote $device
        else
            launch_device_local $device
        fi
    done
    exit 0
}
#No arguments present.  Launch everywhere.
launch_all_devices

