#!/bin/bash
#Author: David Gitz
#Purpose: Kills Software on all Devices

declare -a Devices=("ControlModule1" "ControlModule2" "dgitzrosmaster")
function print_usage()
{
    echo "Usage Instructions"
    echo "-a Stop all Devices"
    echo "-r <device> Stop on remote device"
    echo "-l Stop local Device"
    
}
function stop_device_remote ()
{
    echo "Attempting to stop on remote: " $1 
    ssh robot@$1 "./scripts/stopSystem -l"
}

function stop_device_local ()
{
    read_tasklist
}
function stop_all_devices()
{
    echo "Stopping on all Devices"
    #First attempt a graceful close
    stop_command="rosnode kill --all"
    eval $stop_command
    
    #Then go through all devices to make sure all nodes are stopped.  
    for device in "${Devices[@]}"
    do
        if [ $device != $HOSTNAME ]; then
            stop_device_remote $device
        else
            stop_device_local $device
        fi
    done
    exit 0
}
function read_tasklist()
{
    while IFS='' read -r line || [[ -n "$line" ]] ; do
        index=0
        for i in $(echo $line | tr "\t" "\n")
        do
            if [ $index = 1 ]; then
                kill_process $i
            fi
            let "index += 1"
        done
    done < "/home/robot/config/ActiveTasks"
}
function kill_process()
{
    echo "Killing: " $1
    killall $1
}
#No arguments present.  Launch everywhere.
if [ $# -eq 0 ]; then
    print_usage
fi
if [ "$1" = "-a" ]; then
    stop_all_devices
elif [ "$1" = "-r" ]; then
    stop_device_remote $2
elif [ "$1" = "-l" ]; then
    stop_device_local $HOSTNAME
fi

