#!/bin/bash
#Author: David Gitz
#Purpose: Syncs Software across all devices.

declare -a Devices=("ControlModule1" "dgitzrosmaster")

function sync_config_local()  #This method is not correct, the account my personal development machine is dgitz, not robot.  This should be fixed in the future.
{
    #Determine what the name of the ActiveScenario is:
    ActiveScenario=$(cat /home/robot/config/ActiveScenario)

    #Remove old launch files
    rm -r -f /home/dgitz/catkin_ws/src/icarus_rover_v2/launch/*

    #Copy contents of /home/robot/config/scenarios/<ActiveScenario>/* to /home/dgitz/catkin_ws/src/icarus_rover_v2/launch/
    cp /home/robot/config/scenarios/$ActiveScenario/* /home/dgitz/catkin_ws/src/icarus_rover_v2/launch/

     
}

function sync_config_remote()
{
    #Copy ActiveScenario name over.  This isn't used, just for information.
    rsync -ar /home/robot/config/ActiveScenario robot@$1:/home/robot/config 
    
    #Determine what the name of the ActiveScenario is:
    ActiveScenario=$(cat /home/robot/config/ActiveScenario)
    
    #Remove old launch files
    ssh robot@$device 'rm -r -f /home/robot/catkin_ws/src/icarus_rover_v2/launch/*'

    #Copy contents of /home/robot/config/scenarios/<ActiveScenario>/* to /home/robot/catkin_ws/src/icarus_rover_v2/launch/
    rsync -ar /home/robot/config/scenarios/$ActiveScenario/* robot@$device:/home/robot/catkin_ws/src/icarus_rover_v2/launch/
}

for device in "${Devices[@]}"
do
    if [ $device != $HOSTNAME ]; then
        echo "Syncing with Remote Device: "$device
        sync_config_remote $device
        rsync -avr /home/robot/scripts/* robot@$device:~/scripts
        rsync -avr /home/dgitz/catkin_ws/src/icarus_rover_v2/* robot@$device:/home/robot/catkin_ws/src/icarus_rover_v2
        rsync -avr /home/dgitz/catkin_ws/devel/include/icarus_rover_v2/* robot@$device:/home/robot/catkin_ws/devel/include/icarus_rover_v2/
        rsync -avr /home/dgitz/catkin_ws/build/* robot@$device:/home/robot/catkin_ws/build
        rsync -avr /home/dgitz/catkin_ws/*       robot@$device:/home/robot/catkin_ws
    else 
        echo "Syncing with Local Device: "$device
        sync_config_local $device
    fi
done
