#/***************AUTO-GENERATED.  DO NOT EDIT********************/
#/***Created on:2017-01-27 18:09:31.157893***/
from eROS_Definitions import *

#Armed State Definitions

#Gear Definitions
GEAR_FORWARD = 1
GEAR_PARK = 0
GEAR_REVERSE = -1

#Pin Mode Definitions
PINMODE_UNDEFINED = 0
PINMODE_DIGITAL_OUTPUT = 1
PINMODE_DIGITAL_INPUT = 2
PINMODE_ANALOG_INPUT = 3
PINMODE_FORCESENSOR_INPUT = 4
PINMODE_ULTRASONIC_INPUT = 5
PINMODE_QUADRATUREENCODER_INPUT = 6
PINMODE_PWM_OUTPUT = 7
PINMODE_DIGITAL_OUTPUT_NON_ACTUATOR = 8
PINMODE_PWM_OUTPUT_NON_ACTUATOR = 9
PINMODE_ARMCOMMAND_OUTPUT = 253
PINMODE_ARMCOMMAND_INPUT = 254
PINMODE_NOCHANGE = 255

#Board Mode Definitions
BOARDMODE_UNDEFINED = 0
BOARDMODE_BOOT = 1
BOARDMODE_INITIALIZING = 2
BOARDMODE_SHIELDS_CONFIGURED = 3
BOARDMODE_INITIALIZED = 4
BOARDMODE_RUNNING = 5
BOARDMODE_STOPPED = 6

#Control Group Definitions
CONTROLGROUP_MODE_UNDEFINED = 0
GPIO_PORT_UNDEFINED = 0

#Joint Definitions
JOINTTYPE_UNDEFINED = 0
JOINTTYPE_REVOLUTE = 1
JOINTTYPE_UNKNOWN = 2

#Joint State Definitions
JOINTSTATE_UNDEFINED = 0
JOINTSTATE_INITIALIZING = 1
JOINTSTATE_SEARCHING_FOR_HOME = 2
JOINTSTATE_INITIALIZED = 3
JOINTSTATE_RUNNING = 4
